import Head from "next/head";
import Image from "next/image";
import { useState, useEffect } from "react";
import Banner from "../components/Banner";
import Footer from "../components/Footer";
import Header from "../components/Header";
import LargCard from "../components/LargCard";
import MiddiumCart from "../components/MiddiumCart";
import SmallCard from "../components/SmallCard";
import { data } from "../data";
// import gsap from "gsap";
// import ScrollTrigger from "gsap/ScrollTrigger";

const url = "https://course-api.com/react-prop-types-example";

export default function Home({ exploreData }) {
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);

  const FetchData = async () => {
    try {
      const response = await fetch(url);
      const people = await response.json();
      setLoading(false);
      setItems(people);
      console.log(people);
    } catch (error) {
      console.log(error);
    }
  };
  useEffect(() => {
    FetchData();
  }, [url]);
  console.log(`exploreData`, exploreData);

  if (loading) {
    return (
      <div className="w-full text-center mt-[5rem]">
        <h1 className="text-5xl font-extrabold">Loadding.....</h1>
      </div>
    );
  }

  return (
    <div className=" bg-white text-black">
      <Head>
        <title>Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* headre  */}
      <Header />
      {/* banner  */}
      <Banner />
      {/* main part  */}

      <main className="max-w-7xl mx-auto px-3 sm:px-16">
        <section className="pt-6">
          <h2 className="text-4xl font-semibold pb-5">Explor Nearby</h2>
          {/* get data from server */}
          <div className="md:flex md:flex-wrap gap-5 ">
            {data.map((item) => {
              return <SmallCard key={item.img} {...item} />;
            })}
          </div>
        </section>
        {/**/}
        <section>
          <h1 className="text-4xl py-8 font-semibold">Live anywhere</h1>
          <div
            className="flex space-x-3 overflow-scroll  scrollbar-hide p-3 -ml-3 "
            id="comp"
          >
            {items?.map((item) => {
              return <MiddiumCart key={item.id} {...item} id="comp" />;
            })}
          </div>
        </section>
        <LargCard />
      </main>

      <Footer />
    </div>
  );
}
